name: Create API Link release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    release:
      types: [created, updated]

permissions:
  contents: write

defaults:
  run:
    working-directory: apilink

jobs:
  Release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        update-environment: true
        cache: 'pip' # caching pip dependencies

    # Install python requirements
    - run: pip install -r requirements.txt

    # Create artifacts folder
    - name: Create Artifact Folder
      run: New-Item -Path '${{ github.workspace }}' -Name "Artifacts" -ItemType "directory"

    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Add version stamp
      run: |
        python3 ${{ github.workspace }}/apilink/make_version.py

    # PyInstaller
    - run: >
          pyinstaller.exe --name VU-API-Link
          --distpath="${{ github.workspace }}/Artifacts"
          --clean
          --path="${{ github.workspace }}"
          --icon="www/favicon.ico"
          --add-data="config.yaml;."
          --add-data="www/assets/css/*;www/assets/css"
          --add-data="www/assets/img/*;www/assets/img"
          --add-data="www/assets/js/*;www/assets/js"
          --add-data="www/views/*;www/views"
          --add-data="www/*.png;www/"
          --add-data="www/*.html;www/"
          --add-data="www/*.ico;www/"
          --add-data="upload/img_blank;upload/"
          --hiddenimport="pywin32"
          --hiddenimport="win32timezone"
          --uac-admin
          --noconsole
          server.py

    - uses: ksm2/archive-action@v1
      id: archive
      with:
        format: "zip"
        name: VU-API-Link
        root-directory: ${{ github.workspace }}\Artifacts\VU-API-Link

    # Create the release: https://github.com/softprops/action-gh-release
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.archive.outputs.path }}
        draft: true
        body: |
          Changes in this Release
          - First Change
          - Second Change
