name: Create API Link release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    release:
      types: [created, updated]

permissions:
  contents: write

defaults:
  run:
    working-directory: apilink

jobs:
  Release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        update-environment: true
        cache: 'pip' # caching pip dependencies

    # Install python requirements
    - run: pip install -r requirements.txt

    # Create artifacts folder
    - name: Create Artifact Folder
      run: New-Item -Path '${{ github.workspace }}' -Name "Artifacts" -ItemType "directory"

    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Add version stamp
      run: |
        python3 ${{ github.workspace }}/apilink/make_version.py

    # PyInstaller
    - run: >
          pyinstaller.exe --name VU-API-Link
          --distpath="${{ github.workspace }}/Artifacts"
          --clean
          --path="${{ github.workspace }}/apilink"
          --icon="www/favicon.ico"
          --add-data="www/assets/css/*;www/assets/css"
          --add-data="www/assets/img/*;www/assets/img"
          --add-data="www/assets/js/*;www/assets/js"
          --add-data="www/views/*;www/views"
          --add-data="www/*.png;www/"
          --add-data="www/*.html;www/"
          --add-data="www/*.ico;www/"
          --uac-admin
          --noconsole
          server.py

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        path: VU-API-Link
        directory: ${{ github.workspace }}\Artifacts
        filename: 'VU-API-Link.zip'

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.workspace }}\\Artifacts\\VU-API-Link.zip"
        body: "Draft release"
        draft: true
        allowUpdates: true
